#!/bin/bash

PKG_MAN_SYNC="pacman -Syy"
PKG_MAN_INSTALL="pacman -S"
PKG_MAN_UPGRADE="pacman -Su"

PKGS="
    arc-gtk-theme
    compton
    cronie
    dmenu
    firefox
    flameshot
    fontawesome
    gcc
    i3-gaps
    i3lock
    keepassxc
    lxappearance
    nitrogen
    openvpn
    polybar
    rxvt-unicode
    veracrypt
    vim"
