#!/bin/bash

PKG_MAN_SYNC="pacman -Syy"
PKG_MAN_INSTALL="pacman -S"
PKG_MAN_UPGRADE="pacman -Su"

PKGS="
    arc-gtk-theme
    awesome-terminal-fonts
    compton
    cronie
    dmenu
    firefox
    flameshot
    gcc
    i3-gaps
    keepassxc
    lxappearance
    nitrogen
    openvpn
    rxvt-unicode
    veracrypt
    vim
    nnn
    ranger
    neofetch
    newsboat
    yay
    "

