#!/bin/bash

PKG_MAN_SYNC="pacman -Syy"
PKG_MAN_INSTALL="pacman -S"
PKG_MAN_UPGRADE="pacman -Su"

PKGS="
    i3-gaps 
    dmenu 
    i3status 
    i3lock
    gcc 
    rxvt-unicode 
    firefox
    feh
    compton
    nitrogen 
    lxappearance 
    openvpn 
    cronie 
    keepassxc 
    ttf-font-awesome
    arc-gtk-theme
    veracrypt
    vim
    nnn
    ranger
    neofetch
    newsboat
    "

