#!/bin/bash

PKG_MAN_SYNC="xbps-install -S"
PKG_MAN_INSTALL="xbps-install"
PKG_MAN_UPGRADE="xbps-install -u"

PKGS="

    VeraCrypt
    compton
    cronie
    dmenu
    feh
    firefox
    font-awesome
    gcc
    htop
    i3-gaps
    i3lock
    i3status
    keepassxc
    lxappearance
    nitrogen
    ranger
    openvpn
    pamixer
    pcmanfm
    rxvt-unicode
    unzip
    vim
    xdg-utils
    xrdb
    zip
    "
