#!/bin/bash

PKG_MAN_SYNC="xbps-install -S"
PKG_MAN_INSTALL="xbps-install"
PKG_MAN_UPGRADE="xbps-install -u"

PKGS="
    i3-gaps 
    dmenu 
    i3status 
    i3lock
    gcc 
    rxvt-unicode 
    firefox
    compton
    nitrogen 
    lxappearance 
    openvpn 
    cronie 
    keepassxc 
    font-awesome"

